### ISSUE TITLE
Add html-cov reporter

### ISSUE THREAD

**Issue by limpbrains** [nathanboktae/mocha-phantomjs#10]
Hi, thanks for the great tool.

Can you add support of html-cov/json-cov reporters from mocha.

Thanks

**Comment by nathanboktae** [comment]
Closing this very old issue. `html-cov` requires [jscoverage](https://github.com/tj/node-jscoverage) a native project that has no binary distribution that deprecated. Even TJ says [not to use it](https://github.com/tj/node-jscoverage/commit/a08825e5eb5cfd1499344064015ef30fa9854c1b#diff-1e290ac8433d555bce009b162cb869d0). 

If you need coverage, checkout [mocha-phantomjs-istanbul](https://www.npmjs.com/package/mocha-phantomjs-istanbul) or using blanket.js with hooks (see #99)

**Comment by posva** [comment]
LGTM. :+1:
