### ISSUE TITLE
"serialize cyclic structures"

### ISSUE THREAD

**Issue by OscarGodson** [nathanboktae/mocha-phantomjs#104]
Trying to console.log an object and I just get:

```
TypeError: JSON.stringify cannot serialize cyclic structures.
```

@:

```
at mocha-phantomjs/core_extensions.js:28
at mocha-phantomjs/core_extensions.js:58
```

We're using MooTools and I think it might be something to do with trying to stringify a MooTools Class.

**Comment by tiagodll** [comment]
+1

**Comment by nathanboktae** [comment]
@tiagodll `mocha-phantomjs` has been able to handle circular structures for [4 months now](https://github.com/nathanboktae/mocha-phantomjs/commit/2bb3694803cf9e4eb30e5b279dc26ad93763df19#diff-87f9f313468553837765f405afb94aeb).

**Comment by BillyWM** [comment]
@nathanboktae Is that capability in the version published on npm? I installed mocha-phantomjs today and encountered this when trying to log out a non-DOM object that has circular references by design.

**Comment by nathanboktae** [comment]
Yes it is.
