### ISSUE TITLE
Using xunit output with -f option produces empty file

### ISSUE THREAD

**Issue by rmthamer** [nathanboktae/mocha-phantomjs#114]
mocha-phantomjs -R xunit -f testfile.xml ./testrunner.html

testfile.xml will show up empty.  spec works.

**Comment by jonnyreeves** [comment]
https://github.com/mochajs/mocha/pull/2005 has landed, so we should be good to re-enable xunit reporter file writing?

**Comment by nathanboktae** [comment]
Nothing was ever specifically disabled - it should just work.

**Comment by jonnyreeves** [comment]
Doesn't this conditional prevent the use of the file argument? 

https://github.com/nathanboktae/mocha-phantomjs/blob/master/bin/mocha-phantomjs#L122

**Comment by nathanboktae** [comment]
Ah right, I forgot about that :) I'll remove it shortly.

**Comment by nathanboktae** [comment]
`4.0.2` has that check removed.
