### ISSUE TITLE
Consider supporting slimerjs

### ISSUE THREAD

**Issue by Swatinem** [nathanboktae/mocha-phantomjs#124]
If you havent heard of it already, slimerjs is a dropin replacement for phantomjs based on gecko (though not yet fully headless).

I was able to make it run a precompiled js version of mocha-phantomjs.
But using the coffeescript version fails: https://github.com/laurentj/slimerjs/issues/164

While it is an upstream issue that it is not able to run the coffee version of mocha-phantomjs, I wonder why this requirement exists at all, and if it would be better to simply go with js?

**Comment by nathanboktae** [comment]
[mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core) supports slimerjs now.
