### ISSUE TITLE
Syntax or Parse errors lack information

### ISSUE THREAD

**Issue by shellscape** [nathanboktae/mocha-phantomjs#163]
If the chosen runner html file has syntax/parse errors, the script doesn't provide any information on where the error exists. This could be problematic with more complex runner html files.

For instance, if I declare an object hash incorrectly in a script tag in the html runner, the script outputs `SyntaxError: Parse error` without any additional information.

**Comment by yairEO** [comment]
@nathanboktae - please consider updating the `package.json` to the latest phantomjs version.. also it says on the phantomjs NPM page:

> DEPRECATED
> 
> Pre-2.0, this package was published to NPM as phantomjs. We changed the name to phantomjs-prebuilt at the request of PhantomJS team.
> 
> Please update your package references from phantomjs to phantomjs-prebuilt

**Comment by yairEO** [comment]
Btw, how can I know which `phantomjs` version does my projects' `mocha-phantomjs` uses?
I've installed latest `phantomjs` globally via NPM but still have vague error messages, which the new version should have solved, so I'm puzzled..maybe `mocha-phantomjs` is using some other version..

**Comment by nathanboktae** [comment]
Don't hijack unrelated issues please. See #224 for your first question.

You can use the `-p` option to specify a specific phantomjs binary.
