### ISSUE TITLE
Unsafe JavaScript attempt

### ISSUE THREAD

**Issue by 3rd-Eden** [nathanboktae/mocha-phantomjs#167]
Hey,

I've been trying to get this project running on my local machine. But every time I run the test suite I'm greeted by the following error:

```
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///Users/V1/Projects/unshiftio/url-parse/node_modules/mocha-phantomjs/lib/mocha-phantomjs.coffee. Domains, protocols and ports must match.
```

It might be related to 1.9.8 release of phantomjs: https://github.com/ariya/phantomjs/issues/12697

**Comment by erik-vanlankvelt** [comment]
I'm having the same issue.  Also using gulp-mocha-phantomjs.

**Comment by nathanboktae** [comment]
Yes it is because of the above referenced phantomjs issue. I saw it [while working on `mocha-phantomjs-core` too.](https://travis-ci.org/nathanboktae/mocha-phantomjs-core)

from what I've seen, forcing `phantomjs@1.9.16` will get around this issue.

**Comment by mike-engel** [comment]
@nathanboktae I just tried to install `phantomjs@1.9.16` in both the main project and inside mocha-phantomjs to no avail. I've also tried upgrade mocha, to no avail as well.

**Comment by erik-vanlankvelt** [comment]
Any progress on this?  Not all my tests run due to this error.

**Comment by nathanboktae** [comment]
This is not an issue with `mocha-phantomjs` but phantomjs versions >= 1.9.8 < 2.0, [as evidenced here](https://travis-ci.org/nathanboktae/mocha-phantomjs-core/builds/62510258) by a CI run on `mocha-phantomjs-core`.

I'm going to be focusing on v4 that will move to phantomjs 2, so this will be resolved then. For now, you can force using an older version of phantomjs via the `-p` option if you are blocked.

**Comment by halleycarleton** [comment]
@nathanboktae 
> from what I've seen, forcing phantomjs@1.9.16 will get around this issue.

Are you referring to forcing the npm package `phantomjs` to `phantomjs@1.9.16`? If so I tried this and it still installs version 1.9.8 of PhantomJS.
```
$ ./node_modules/phantomjs/lib/phantom/bin/phantomjs -v
1.9.8
```

Is there a workaround that will solve this until `v2.0.0` is stable on linux?

**Comment by nathanboktae** [comment]
> If so I tried this and it still installs version 1.9.8 of PhantomJS.

Correct I was mistaken.

Install phantomjs 1.9.16 yourself then use the `-p`  option to use that phantomjs.

**Comment by halleycarleton** [comment]
The npm package or the actual software?

I tried that with the npm package, and I don't see a v1.9.16 of [PhantomJS](http://phantomjs.org/release-1.9.html).

**Comment by halleycarleton** [comment]
Alright, I built PhantomJS 1.9.7 from source by following [these instructions](http://phantomjs.org/build.html), except instead of `git checkout 2.0` I used `git checkout 1.9.7`.

Then I changed the PhantomJS path in my mocha-phantomjs test command from `./node_modules/phantomjs/lib/phantom/bin/phantomjs` to `/usr/bin/phantomjs`(which is a symlink).

This has fixed this issue for me.

**Comment by nathanboktae** [comment]
> Alright, I built PhantomJS 1.9.7 from source

Ouch, there are [built versions available](https://github.com/nathanboktae/mocha-phantomjs-core/blob/master/.travis.yml#L10) for 1.9.7 FYI.

**Comment by halleycarleton** [comment]
Hmm, I didn't see any information about built older versions on the PhantomJS website, or through a quick google search. Oh well, it only took around 40-60 min to build and my work day was over anyways.

**Comment by Inviz** [comment]
Broke our Travis.

**Comment by nathanboktae** [comment]
> Why would you do this in minor version

Right it shouldn't have been. My bad I'll revert the dependency version and republish, then publish a minor bump.

And in v4 it'll be a direct dependency avoiding the problem.

**Comment by nickp10** [comment]
This change has caused an issue with the gulp-mocha-phantomjs module. I'm not entirely sure how the dependency versions are working, but gulp-mocha-phantomjs is allowing phantomjs 1.9.17, where this change is only allowing up to 1.9.15. This results in the following error:

> npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer mocha-phantomjs@3.5.4 wants phantomjs@1.9.1 - 1.9.7-15

The workaround is to explicitly reference phantomjs 1.9.15 in my package.json file.
