### ISSUE TITLE
Add documentation for coverage

### ISSUE THREAD

**Issue by andrewhood125** [nathanboktae/mocha-phantomjs#172]
Awesome package! I've been in Javascript testing hell for the past week or so. Long story short I wrote my first javascript package and I'm trying to get it hooked into Travis and Coveralls. I was able to use Mocha from the cli but I couldn't cover anything that used jQuery in my code. If I went to a browser based solution I couldn't run from the cli. 

Enter mocha-phantomjs. It's exactly what I needed. I'm having trouble figuring out how I can hook into blanket or Istanbul though to produce coverage info for coveralls. I'd like to lend a hand and help out here. I'm going to dig in and try and figure out how to incorporate them but I'd appreciate any advice if someone has already solved this problem.

**Comment by nathanboktae** [comment]
Yup we need documentation on this. Currently your best documentation is in #99 [here](https://github.com/metaskills/mocha-phantomjs/issues/99#issuecomment-26861239)

**Comment by nathanboktae** [comment]
Actually I didn't know this existed until just now - [mocha-phantomjs-istanbul](https://www.npmjs.com/package/mocha-phantomjs-istanbul)

**Comment by nathanboktae** [comment]
So, how did you solve your problem?

**Comment by SpaceK33z** [comment]
I would also like to know how you solved this, because mocha-phantomjs-istanbul seems to not work anymore.
