### ISSUE TITLE
Transfer ownership?

### ISSUE THREAD

**Issue by metaskills** [nathanboktae/mocha-phantomjs#193]
Nathan, I have not worked on this in a while and you are clearly owning it :)

Would you like to attempt transferring this to you github account? I have never done it before but from my understanding it should create automatic redirects and all. Thoughts?

**Comment by nathanboktae** [comment]
Yes sure I'd be glad too. :) if the redirects don't work at least we can update npm.

**Comment by metaskills** [comment]
@nathanboktae Did it work? It said the request was sent to you.

**Comment by nathanboktae** [comment]
It did. Thanks for all the great work.
