### ISSUE TITLE
Unlock or extend the range of acceptable PhantomJs modules

### ISSUE THREAD

**Issue by lmarkus** [nathanboktae/mocha-phantomjs#194]
See: https://github.com/jdcataldo/grunt-mocha-phantomjs/issues/36#issuecomment-121789305

**Comment by shellscape** [comment]
:+1: what's the deal with this? Shouldnt the dep be defined as ^1.9.1 instead of ~1.9.1? This is causing major breakage in our tools, especially with gulp-mocha-phantomjs.

**Comment by nathanboktae** [comment]
The issue is detailed in #167. PhantomJS 1.9.8 has a bug that is causing breaks for other people.

I have republished 3.5.6 with the `~1.9.8` depedency range, and I'll set the `1.9.1 - 1.9.7-15` for 3.6.0.

**Comment by lmarkus** [comment]
Thanks!

**Comment by shellscape** [comment]
Thank you!
