### ISSUE TITLE
`npm install` fails dependencies even with phantomjs

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [nathanboktae/mocha-phantomjs#195]
As of about a couple days ago, the following errors are popping up in all of my grunt builds using mocha-phantomjs:

    error Windows_NT 6.3.9600
    error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
    error node v0.12.7
    error npm  v2.11.3
    error code EPEERINVALID
    error peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
    error peerinvalid Peer mocha-phantomjs@3.5.6 wants phantomjs@~1.9.1

Installing `"phantomjs": "~1.9.X"` (or adding it to package.json's dependencies) doesn't change it.

Here's a [travis-ci example](https://travis-ci.org/FullScreenShenanigans/FullScreenMario/builds/71586238).

Edit: This seems to also be popping up elsewhere, https://github.com/google/material-design-lite/issues/1089

**Comment by nathanboktae** [comment]
Upgrade to `grunt-mocha-phantomjs@0.7.0`

**Comment by JoshuaKGoldberg** [comment]
Thanks!
