### ISSUE TITLE
Mocha.process.stdout not working properly?

### ISSUE THREAD

**Issue by jchoi18** [nathanboktae/mocha-phantomjs#197]
Except when using JSON as reporter, I believe the mocha.process.stdout isn't working properly. For example in the mocha-phantomjs.coffee, even if I comment out the following code:
@page.onConsoleMessage = (msg) -> system.stdout.writeLine(msg)

I should still see the test results from the following right?
    @page.onCallback = (data) =>
      if data?.hasOwnProperty 'Mocha.process.stdout.write'
        @output.write data['Mocha.process.stdout.write']

But instead, all test results / client side console messages seem to be getting captured by the  browser console. If I comment out the first line, nothing gets output on my terminal. (except when using json, json outputs fine) 

I'm trying to do this since the application I'm testing has a lot of noise on the client side (events firing, etc.) and I want to be able to block them out in my tests. Also I believe this is causing all the test output to have no color formatting (green / red colors). 

Just wondering, where is the code exactly telling mocha to output to Mocha.process.stdout? I tried looking in individual reporter files but they all have the regular process.stdout.

**Comment by nathanboktae** [comment]
See #114, #189, #161 . TL;DR is like you found that moat mocha reporters use `console.log` so its impractical to separate the noise out.
