### ISSUE TITLE
Update phantomjs peerDependency to 1.9.18

### ISSUE THREAD

**Issue by guybedford** [nathanboktae/mocha-phantomjs#199]
As far as I can tell this will work against 1.9.18, it would be great to have the peerDependency range updated for this if possible.

**Comment by nathanboktae** [comment]
It doesn't actually. Due to #167 (caused by ariya/phantomjs#12697), I am capping the range. If you need a higher version for some reason and can deal with the bug, `mocha-phantomjs@3.5.6` is exactly the same as 3.6.0 except for the phantomjs peerDependency.

**Comment by guybedford** [comment]
Ok excellent, that should work well then, thanks for your help.
