### ISSUE TITLE
Phantomjs 1.9.x  can no longer run CoffeeScript

### ISSUE THREAD

**Issue by Vanuan** [nathanboktae/mocha-phantomjs#200]
https://github.com/ariya/phantomjs/issues/12410

**Comment by nathanboktae** [comment]
It says right at the bottom its for `2.0` only. I've already broken out the phantomjs code into [mocha-phantomjs-core](HTTPS://github.com/nathanboktae/mocha-phantomjs-core) that is es5 javascript with CI tests passing on 2.0 and 1.9.7.

**Comment by Vanuan** [comment]
phantomjs 1.9.0 doesn't work either.

**Comment by nathanboktae** [comment]
The readme states in big bold letters that [since 3.0](https://github.com/nathanboktae/mocha-phantomjs/commit/f096f57058bfc2f55bb5e94ee48be56fed3a0c86#diff-04c6e90faac2675aa89e2176d2eec7d8) we've required a minimum of `1.9.1`.
