### ISSUE TITLE
phantom js 1.9.x head is at 1.9.18

### ISSUE THREAD

**Issue by Pomax** [nathanboktae/mocha-phantomjs#201]
So the `1.9.1 - 1.9.7-15` requirement fails when `1.9.18` is installed

additionally, there is no `1.9.7-15`, according to the https://github.com/Medium/phantomjs tag list, it tops out at `1.9.7-14`, then switches to `1.9.8`

**Comment by nathanboktae** [comment]
See #199, #167, and the readme `Installation` section.

**Comment by Pomax** [comment]
Thanks. After reading them, though, there does not seem any mention of the fact that mocha-phantom still has a peer dependency for a version that literally does not exist, on https://github.com/nathanboktae/mocha-phantomjs/blob/master/package.json#L46

Changing that line to `1.9.1 - 1.9.7-14`, so that it covers a range of real tags, instead, would make a lot of sense.

**Comment by nathanboktae** [comment]
> has a peer dependency for a version that literally does not exist

It literally does. http://registry.npmjs.org/phantomjs/1.9.7-15

**Comment by Pomax** [comment]
that makes no sense, there is no 1.9.7-15 release on github by Medium...

**Comment by nathanboktae** [comment]
You are misunderstanding how npm and the registry works. It's completely disjunct from GitHub (vs bower and other package managers). at some point Medium typed `npm publish` with the `version` field in the `package.json` set to `1.9.7-15` and then published the artifacts up to `registry.npmjs.org`. Those artifacts are served when you `npm install phantomjs@1.9.7-15`. GitHub, git, or any source control are not required to publish to the npm registry.

**Comment by Pomax** [comment]
No, I get that. My point was that 1.9.7-15 was, from what I can tell, not intended to be in the official releases list, and so despite it existing on npm, there's no official support for it, and as such it doesn't make sense to keep it as part of the version range for mocha-phantomjs.

Up to you of course, but if Medium doesn't acknowledge it, pointing to it might cause if Medium decides to clean up its release version list to match its own official releases list.

**Comment by nathanboktae** [comment]
> there's no official support for it

Medium just wrote a wrapper around the real phantomjs. He doesn't maintain the actual binary. In fact, node package `phantomjs@1.9.18` actually installs phantomjs 1.9.8 *facepalm*

```
~/temp/derp
 1:13PM ᐅ npm install phantomjs@1.9.18
/
> phantomjs@1.9.18 install /Users/nblack/temp/derp/node_modules/phantomjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/81/0crqt_td7nj1v7gwscvg9x9c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [========================================] 99% 0.0s
Received 9187K total.
Extracting zip contents
Removing /Users/nblack/temp/derp/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/81/0crqt_td7nj1v7gwscvg9x9c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1442002417102/phantomjs-1.9.8-macosx -> /Users/nblack/temp/derp/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/nblack/temp/derp/node_modules/phantomjs/lib/phantom/bin/phantomjs
phantomjs@1.9.18 node_modules/phantomjs
├── which@1.0.9
├── progress@1.1.8
├── kew@0.4.0
├── adm-zip@0.4.4
├── request-progress@0.3.1 (throttleit@0.0.2)
├── npmconf@2.1.1 (uid-number@0.0.5, ini@1.3.4, inherits@2.0.1, once@1.3.2, semver@4.3.6, osenv@0.1.3, config-chain@1.1.9, nopt@3.0.4, mkdirp@0.5.1)
├── request@2.42.0 (caseless@0.6.0, aws-sign2@0.5.0, forever-agent@0.5.2, oauth-sign@0.4.0, stringstream@0.0.4, tunnel-agent@0.4.1, json-stringify-safe@5.0.1, qs@1.2.2, node-uuid@1.4.3, mime-types@1.0.2, tough-cookie@2.0.0, http-signature@0.10.1, bl@0.9.4, hawk@1.1.1, form-data@0.1.4)
└── fs-extra@0.23.1 (path-is-absolute@1.0.0, graceful-fs@4.1.2, jsonfile@2.2.1, rimraf@2.4.3)

~/temp/derp
 1:14PM ᐅ ./node_modules/phantomjs/bin/phantomjs --version
1.9.8
```

**Comment by Pomax** [comment]
wow, that's glorious....
