### ISSUE TITLE
peerDependency phantomjs version causing install error

### ISSUE THREAD

**Issue by stevenvachon** [nathanboktae/mocha-phantomjs#202]
```
npm ERR! peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15
```

Please remove `peerDependencies` and simply use `dependencies`.

**Comment by nathanboktae** [comment]
Yes 4.0 beta already has phantomjs as a direct dependency. For now explicitly require `phantomjs@1.9.7-15`
