### ISSUE TITLE
use require.resolve to fetch script file of mocha-phantomjs-core

### ISSUE THREAD

**Issue by kaelzhang** [nathanboktae/mocha-phantomjs#204]
The new `NPM`(version 3.3.3) will install dependencies directly into the `node_modules` directory as much as possible rather than installing them hierarchically.

So, there might not be a `node_modules` directory inside `node_modules/mocha-phantomjs/`, see [here](https://github.com/nathanboktae/mocha-phantomjs/blob/master/bin/mocha-phantomjs#L96)

It's better to do the `path.resolve` thing with `require.resolve()`

**Comment by nathanboktae** [comment]
Good catch, thanks.

**Comment by nathanboktae** [comment]
`4.0.1` has your fix. Thanks.

**Comment by kaelzhang** [comment]
You are so efficient, buddy! :+1:

**Comment by nathanboktae** [comment]
Yeah 10min from open to fix and published is a  new record for me :)
