### ISSUE TITLE
is it possible to not show console logs?

### ISSUE THREAD

**Issue by yairEO** [nathanboktae/mocha-phantomjs#220]
inside the code which I'm testing I have *console logs* (or other console types) and they show up when I run mocha-phantomjs. 

![phantomjs console logs](https://cloud.githubusercontent.com/assets/845031/11215978/81a46540-8d51-11e5-9922-68c6ec316f17.png)

**Comment by nathanboktae** [comment]
No. The `spec` reporter and your code [use `console.log`](https://github.com/mochajs/mocha/blob/c4393c456839d6bf2cbb4abb1cd177010ee06458/lib/reporters/spec.js#L61) so it's all the same stream. See #114.

**Comment by yairEO** [comment]
ok then, I will just use `gulp-strip-debug`. Thanks for the quick reply!

**Comment by nathanboktae** [comment]
Yup some kind of `grep` solution should work for you. Good luck!
