### ISSUE TITLE
Use this as a bridge?

### ISSUE THREAD

**Issue by dschinkel** [nathanboktae/mocha-phantomjs#226]
So is mocha-phantomjs a phantom-to-node bridge?  

If so, if I want to start using the Phantom API, what syntax should I use?  I mean there are other bridges out there like phantomjs-node which have their own wrapper syntax but what if I'm using mocha-phantomjs?

example lets say I want to do this in my some-spec.js:

```
before(function() {
    phantom.create().then(function(ph) {
        ph.createPage().then(function(page) {
            page.open('https://stackoverflow.com/').then(function(status) {
                status = status
            })
        });
    });
})
```

the above is phantomjs-node syntax as I have phantom = require('phantom') at the top of my file.  So would I use phantomjs-node in conjunction with mocha-phantomjs or what?  

I'm able to run my tests through my test-runner.html but then I really just want to run this via command-line like I have been which is mocha-phantomjs test/features/specs/test-runner.html which works as in I can get my test to pass without the phantom api stuff.  Once I try to introduce the phantom code above, it bombs after I bundle my spec.

**Comment by dschinkel** [comment]
so you run mocha tests with 'mocha ...'.  I am just wondering if I am using your client, is there anything special that I need to add to the command-line...or phantom page code should just "work" since I have the require and then just run whatever command I usually do with mocha..right?

**Comment by dschinkel** [comment]
Because when I run this with 'mocha some-spec.js' I get TypeError: phantom.create(...).then is not a function

**Comment by dschinkel** [comment]
I am just trying to understand if anyone out there is using this like I'm trying here and why it would be failing like this?  if I have your bridge in my require and using that to call commands on it, why would it fail?

**Comment by dschinkel** [comment]
what I essentially want to do is something like this with mocha http://www.redotheweb.com/2013/01/15/functional-testing-for-nodejs-using-mocha-and-zombie-js.html

So is all I need is mocha-phantomjs meaning I can require('mocha-phantomjs') and it provides a wrapper (bridge) to phantom so I can create page objects and work with that in my tests?

**Comment by nathanboktae** [comment]
> So is mocha-phantomjs a phantom-to-node bridge?

No, it's not. It's a way to use phantomjs as your browser to test your **client side** mocha tests in that browser. Node.js is used as the command line parser and npm as the distribution mechanism, but that's it. The core brains is in [mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core) which that project has no Node.js

Mocha runs in the browser, so you write browser tests in Mocha. Just as if you were to run your browser tests in mocha by opening Chrome and going to `file://foo/bar/tests.html` or whatever the URL is, you instead use `mocha-phantomjs` to run those client side tests and output the results using other mocha reporters to the console.

If you want to write tests where your driving phantom clicking a page, there are other drivers for it like you linked to zombie.js or whatnot.

**Comment by dschinkel** [comment]
ok so when you say "you write browser tests in Mocha" you would just work with the DOM (window, ect), not the phantomJS page object?

**Comment by dschinkel** [comment]
I think it would be very helpful to have more of an intro on your mocha-phantomjs page.  For someone new to this, you just dive into getting it installed and really don't explain the use case for using it or use cases.  I get that it allows you to run mocha tests in the browser, ok fine but then what's the use case around that with tests.  I think it would be helpful to show examples of mocha tests.  The tests that are core to moch-phantomjs lib doesn't work with any DOM elements, etc. because it's core code, so having some additional test examples using mocha running in the .html would be nice.

**Comment by nathanboktae** [comment]
Yes, the tests run in the browser, so you can internally fill in form using DOM APIs and such. Or more unit-style tests, whatever - but you're running inside the page.

If you go the casper route I'll point you to [mocha-casperjs](https://github.com/nathanboktae/mocha-casperjs), but there's lots of options in this space including [Nightmarejs](https://github.com/segmentio/nightmare), which uses [Electron](http://electron.atom.io/) instead of phantomjs so it's not truly headless (similarly you can use [slimerjs](https://github.com/laurentj/slimerjs) with casperjs)

**Comment by dschinkel** [comment]
thanks nathan!
