### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by erikvold** [nathanboktae/mocha-phantomjs#230]
In the readme there is a `callPhantom` function used in an example and there is not description for what that is or what it does.  Also there appears to only be one example which is very specific to testing only js that is used in the browser, and it is unclear to me how I would test a html page that I would actually use in a production environment for example.

**Comment by nathanboktae** [comment]
It is phantomjs' hook to call the API side from the browswer. Personally I would not use it but people kept asking for it so I took the PR. Basically if you do you can't run your tests in a normal browser.
