### ISSUE TITLE
Bind polyfill fails in angular 1.5.x

### ISSUE THREAD

**Issue by npbenjohnson** [nathanboktae/mocha-phantomjs#235]
I've verified this polyfill works https://github.com/tom-james-watson/phantomjs-polyfill/blob/master/bind-polyfill.js
Discussion about the error: johnpapa/generator-hottowel#154

**Comment by nathanboktae** [comment]
How is this `mocha-phantomjs` 's problem?

**Comment by npbenjohnson** [comment]
It has a built in polyfill in browser-shim.js that doesn't behave in a way that meets the MDN spec, accepted polyfill can be found on the documentation for bind [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)

**Comment by nathanboktae** [comment]
Got it, thanks. I [updated `mocha-phantomjs-core`](https://github.com/nathanboktae/mocha-phantomjs-core/commit/d6003d7ffdb21d276069ee3c9b895c05c0dc18ec). I need to update this.

**Comment by nathanboktae** [comment]
`mocha-phantomjs-core@1.3.1` has been published
