### ISSUE TITLE
Update to phantomjs dep to phantomjs-prebuilt

### ISSUE THREAD

**Issue by jdalton** [nathanboktae/mocha-phantomjs#239]
The package [phantomjs](https://www.npmjs.com/package/phantomjs) has been renamed [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt).

**Comment by nathanboktae** [comment]
See #224

**Comment by jdalton** [comment]
Ah, the earliest version of `phantomjs-prebuilt` is v2.1.2. Cool cool.
