### ISSUE TITLE
Error codes should be exposed to terminal

### ISSUE THREAD

**Issue by cormacmccarthy** [nathanboktae/mocha-phantomjs#242]
Running mocha-phantomjs from terminal should result in proper exit codes being exposed to terminal processes. Right now, they do not seem to be:

![image](https://cloud.githubusercontent.com/assets/8006971/18009458/5d3f09fa-6b7a-11e6-9f5e-4dc56c651098.png)

Here are my test files:

`test/index.html`
```
<!DOCTYPE html>
<html>
	<head>
		<title>Example Unit Tests</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="../node_modules/mocha/mocha.css" />
		<script src="../node_modules/requirejs/require.js"></script>
	</head>
	<body>
		<div id="mocha"></div>

		<script>
			var Fuel = Fuel || {};
			/* global blanket:true */
			(function onPageLoad () {
				// base config
				var requireConfig = {
					baseUrl: './',
					paths: {
						chai: '../node_modules/chai/chai',
						mocha: '../node_modules/mocha/mocha',
						tests: './tests'
					}
				};

				require.config(requireConfig);

				require(['tests'], function noop () {});
			})();
</script>
	</body>
</html>
```

`test/tests.js`
```
define(function tests (require) {
	require('mocha');
	var chai = require('chai');
	var assert = chai.assert;

	mocha.setup('bdd');

	describe('Exit codes', function() {
		it('Should fail with an exit code', function() {
			assert.isOk(false, 'forcing failure');
		});
	});

	mocha.run();
});
```

Here is the terminal command I am running:
`mocha-phantomjs test/index.html && echo "this should not appear if tests failed"`

Running `mocha-phantomjs test/index.html` in this instance follow by `echo $?` ought to result in a non-zero integer being echo'd to the terminal.

The reason this is important is that I need to be able to run my mocha tests before I kick off other processes (like building). If the tests fail, I don't want to run the other processes:

`npm run test && npm run package`

**Comment by acthp** [comment]
I'm having this problem, too: exit codes are wrong. However, it's only happening on some systems, even with the same version of mocha-phantomjs. All systems report the same test failures, but some do not return the correct error code to the shell.

**Comment by nathanboktae** [comment]
I have [extensive tests around the exit code](https://github.com/nathanboktae/mocha-phantomjs/blob/master/test/mocha-phantomjs.coffee#L35) - it's asserted nearly every test. You'll have to provide more information about what these systems that are failing - is and version, phantomjs version and node.js version.

**Comment by acthp** [comment]
I don't have more time to spend on this, but things I tried:

I checked versions of mocha-phantomjs, mocha, mocha-loader (for webpack), phantomjs, and finally used npm-shrinkwrap to ensure all code was the same between failing & working systems. None of this helped.

I then switched the failing system from ubuntu 12.04 to 14.04, and it started working correctly. So, could be a node or npm version problem, or some other thing associated with the ubuntu version.

The failing systems were on circle-ci, which supports 12.04 and 14.04.

On a 12.04 build, versions are

```
ubuntu@box1529:~$ node --version
v0.10.33
ubuntu@box1529:~$ npm --version
2.13.5
```

On a 14.04 build, versions are

```
ubuntu@box1672:~$ node --version
v4.2.6
ubuntu@box1672:~$ npm --version
2.14.12
```

So, old version of node, perhaps.

**Comment by nathanboktae** [comment]
> So, old version of node, perhaps.

Yes since #237 we've been using `process.exitCode` which was [added in node 0.11](https://nodejs.org/api/process.html#process_process_exitcode). I'll update `package.json` to reflect the new node version requirement.
