### ISSUE TITLE
"'undefined' is not a function (evaluating 'mocha.ui('bdd')')"

### ISSUE THREAD

**Issue by Nanofus** [nathanboktae/mocha-phantomjs#243]
Hi! I'm trying to run some tests using the following HTML:

```
<html>
  <head>
    <meta charset="utf-8">
    <!-- encoding must be set for mocha's special characters to render properly -->
    <link rel="stylesheet" href="../node_modules/mocha/mocha.css" />
  </head>
  <body>
    <div id="mocha"></div>
    <script src="../node_modules/mocha/mocha.js"></script>
    <script src="../node_modules/chai/chai.js"></script>
    <script>
      mocha.ui('bdd')
      expect = chai.expects
    </script>
    <script src="../browserMqtt.js"></script>
    <script src="../main.js"></script>
    <script src="test.js"></script>
    <script>
      mocha.run()
    </script>
  </body>
</html>
```

I double-checked the file paths, they are all correct. If I `console.log(mocha.ui)` it returns the correct function. However, when I run `mocha-phantomjs`, I get the following error:

```
TypeError: 'undefined' is not a function (evaluating 'mocha.ui('bdd')')
```

I'm on Windows 10, `phantomjs` version is 2.1.1, `mocha` version is 2.4.5 and `mocha-phantomjs` version is 4.0.2.

Thanks in advance!

**Comment by nathanboktae** [comment]
Do the tests pass in your browser?

**Comment by Nanofus** [comment]
Yes, they work fine in the browser.

**Comment by g-gabber** [comment]
Change the windows backslash (`\`) to unix slash (`/`) in the test runner file path.
For example C:/dev/test/runner.html

**Comment by nathanboktae** [comment]
Closing without more information. `mocha.ui('bdd')` is used [everywhere in the tests.](https://github.com/nathanboktae/mocha-phantomjs/search?utf8=%E2%9C%93&q=bdd)
