### ISSUE TITLE
travis ci build failing on no-colors test

### ISSUE THREAD

**Issue by omouse** [nathanboktae/mocha-phantomjs#244]
no-colors by default will output in color is the failing test

you can see the output in the build: https://travis-ci.org/nathanboktae/mocha-phantomjs/builds/159069819

I think the issue is with the regex being used for matching, may have to do with the unicode character matching. I haven't investigated further yet, just wanted to let you know the travis ci build's failing at the moment

**Comment by omouse** [comment]
a little late but thanks @nathanboktae for fixing this issue! 😄

**Comment by nathanboktae** [comment]
Thank you for reporting it !
