### ISSUE TITLE
Mac OS Sierra cannot run PhantomJS 1.9.7

### ISSUE THREAD

**Issue by paulrutter** [nathanboktae/mocha-phantomjs#245]
When running mocha-phantomjs (or plain PhantomJS for that matter) on the new Mac OS Sierra, it fails with the following error:

> phantomjs terminated with signal SIGSEGV

Upgrading to a newer PhantomJS version solves this issue (i'm using 2.1.7 right now).
I found several issues in the past which requested a newer PhantomJS version, but these were rejected.
I do think that we cannot reject it any longer, as Mac OS Sierra no longer works with this older version.

@nathanboktae what do you think? I can file a PR if needed.

**Comment by latel** [comment]
same issue here, no idea what to do

**Comment by nathanboktae** [comment]
1. Use the `-p` option to specify a different phantomjs binary.
2. Switch to [mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core). I will eventually add the same CLI interface to that project as this one and then it will be basically the same as this one but without a direct binary dependency.

distributing the phantomjs binary has been a bag of hurt (#167, #231, #224) and I'm not going to do it going forward. `mocha-phantomjs-core` will be the future, and with the CLI and even some shell wrappers it'll feel the same project.

**Comment by latel** [comment]
I switched to mocha-phantomjs-core
