### ISSUE TITLE
Add junit xml format.

### ISSUE THREAD

**Issue by g-gabber** [nathanboktae/mocha-phantomjs#246]
There is mocha-junit-reporter and mocha-jenkins-reporter reports. But they require nodejs context.
It would be great to add junit reporter.

**Comment by g-gabber** [comment]
Sorry, never mind.
xunit is a superset of junit.
This issue can be closed.

**Comment by nathanboktae** [comment]
Moreover, just write a [custom reporter](https://github.com/mochajs/mocha/wiki/Third-party-reporters) and [use it in mocha-phantomjs](https://github.com/nathanboktae/mocha-phantomjs#third-party-reporters).
