### ISSUE TITLE
Separate console output and test results

### ISSUE THREAD

**Issue by Nithanaroy** [nathanboktae/mocha-phantomjs#247]
`./node_modules/mocha-phantomjs/bin/mocha-phantomjs -p /Applications/phantomjs-2.1.1-macosx/bin/phantomjs ./test/index.test.html --ignore-resource-errors` prints to stdout - console.logs, console.warns, console.errors and **test results** intermingled. Would be really nice if we can separate everything into groups or turn off console output completely.

**Comment by nathanboktae** [comment]
See #189, #114, #161.
