### ISSUE TITLE
phantomjs package deprecated

### ISSUE THREAD

**Issue by szkrd** [nathanboktae/mocha-phantomjs#248]
Probably __phantomjs-prebuilt__ should be used.

Warning is here:
https://www.npmjs.com/package/phantomjs

New npm is here:
https://www.npmjs.com/package/phantomjs-prebuilt

**Comment by frediana** [comment]
Definitely, this is causing some trouble on Mac OsX Sierra otherwise.

I can push a Pull Request for this

**Comment by sonnyp** [comment]
https://github.com/nathanboktae/mocha-phantomjs/pull/224#issuecomment-176291314

**Comment by nathanboktae** [comment]
See #224, #245, tl;dr use [mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core) . Though these days I would also switch to [mocha-chrome](https://github.com/shellscape/mocha-chrome) since PhantomJS is dead in general, and Chome and Firefox can run headless.
