### ISSUE TITLE
Output file no data

### ISSUE THREAD

**Issue by appzone** [nathanboktae/mocha-phantomjs#252]
Hi, i try outping the result into file with following command

mocha-phantomjs -R spec -f output index.html

the "output" file is created, but its empty
and the output also appear in console.

**Comment by nathanboktae** [comment]
The spec reporter doesn't use `process.stdout.write` but rather `console.log` - see #114 for more information.

Simply use your shell piping for that scenario:

```
mocha-phantomjs -R spec index.html > output
```
