### ISSUE TITLE
Calling phantomJS function

### ISSUE THREAD

**Issue by appzone** [nathanboktae/mocha-phantomjs#253]
Hi, how can i call phantomJS function with mocha-phantomJs ? 

let say i want to call
page.open(url, function (status) {
  //Page is loaded!
  phantom.exit();
});

how i do that in mocha-phantomjs ? 
i read there is a callPhantom(), but how i use that ? thanks

**Comment by nathanboktae** [comment]
Why? What are you trying to do? For a page load, you can just repond to `DOMContentLoaded` in the browser.

**Comment by appzone** [comment]
i am trying to do page automation. 
like this url http://phantomjs.org/page-automation.html

i am trying to achieve something like this

`
describe("Checkout from merchant", function() {
  	it("Should return application ID", function(){
			==> do some phantomJS page automation
  	});

  });
`

is it possible ?

**Comment by appzone** [comment]
btw i find another solution. separate between mocha and phantomjs instance

but i just want to know if is it possible to do like my comment description upper.

thanks

**Comment by nathanboktae** [comment]
This is not the project you want. It is not for externally automating page crawls. Please use [mocha-casperjs](https://github.com/nathanboktae/mocha-casperjs) or (Nightmare.js)[https://github.com/segmentio/nightmare]. I'd recommend the later as it uses the more modern Electron, as phantomjs is far behind, based on QT5 and [without maintainers](https://www.infoq.com/news/2017/04/Phantomjs-future-uncertain).
