### ISSUE TITLE
Low contrast terminal output with corrupt characters

### ISSUE THREAD

**Issue by themightychris** [nathanboktae/mocha-phantomjs#255]
I'm on an Ubuntu 16.04 desktop, any ideas why my CLI output is so rough?

![screenshot from 2017-08-18 10-08-59](https://user-images.githubusercontent.com/458494/29462492-8aa48888-83fd-11e7-8f69-e5b1ec1579b2.png)

**Comment by nathanboktae** [comment]
The `spec` reporter uses Unicode characters so your terminal needs to use utf8 and a font with those glyphs. It's likely the former in your case.

**Comment by themightychris** [comment]
Seems like my terminal does support unicode (stock ubuntu 16.04 desktop), I switched between a few fonts. Any idea what code that glyph is supposed to be so i can verify explicitly ?

![screenshot from 2017-08-18 15-56-53](https://user-images.githubusercontent.com/458494/29475476-e7f0a7a8-842d-11e7-982d-8b0326af95c7.png)

**Comment by nathanboktae** [comment]
https://github.com/mochajs/mocha/blob/master/lib/reporters/base.js#L80-L93

Closing this out (see our [travis ci builds](https://travis-ci.org/nathanboktae/mocha-phantomjs) to see the checkmark come out in color).
