### ISSUE TITLE
Please Updae Phantomjs Version

### ISSUE THREAD

**Issue by orangebook** [nathanboktae/mocha-phantomjs#259]
<img width="608" alt="2017-12-28 1 29 30" src="https://user-images.githubusercontent.com/7347198/34401122-687c9104-ebd3-11e7-9e26-424d93dbbec6.png">
I can i solve first example.

**Comment by orangebook** [comment]
@nathanboktae -R could not useful
Now, I use -p param to run my test.If you are busy busy , could I post pull Request to you?

**Comment by nathanboktae** [comment]
See #224, #245, tl;dr use [mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core) . Though these days I would also switch to [mocha-chrome](https://github.com/shellscape/mocha-chrome) since PhantomJS is dead in general, and Chome and Firefox can run headless.
