### ISSUE TITLE
Cannot get --setting to work (to enable CORS)

### ISSUE THREAD

**Issue by dominicbarnes** [nathanboktae/mocha-phantomjs#59]
I can't seem to get `--setting` to work for my script, or perhaps I don't understand how it works. Is it supposed to be a collection of settings like the ones for the PhantomJS command line (as documented [here](https://github.com/ariya/phantomjs/wiki/API-Reference)?)

I'm trying to allow my test script to run cross-domain (CORS) requests as part of my test. The options I think I need are `--web-security=false` and `--local-to-remote-url-access=true` but no permutations of those options passed to mocha-phantomjs seem to work. I've tried renaming the params to `webSecurity` and `webSecurityEnabled` but it's just not working.

If I modify mocha-phantomjs bin to adjust `spawnArgs`, I get some different results, but it breaks mocha-phantomjs.coffee since it's expecting a specific set of params.

Thanks!

**Comment by yairEO** [comment]
so how are should `--setting` be used? README doesn't say and here nobody gave any explanation
